### ISSUE TITLE
Имплементация логики пагинации для списка проектов и issue

### ISSUE THREAD

**Issue by Artiomtb** [a-panchenko/BugTracker#1]
Нужно переписать логику выбора issue и project таким образом, чтобы выбиралось определённое фиксированное на сервере количество за раз - добавить необязательный параметр page - если его нет - выгружать первую.

Пример best-practice select с пагинацией:

``` sql
select * from (
    select /*+ FIRST_ROWS(20) */ a.*, ROWNUM rnum
    from (select * from emp order by id ) a 
    where ROWNUM <= 20
) where rnum  >= 10; 
```
- выгрузит из таблицы emp строки с 10 по 20 включительно.

Пример:
/project?id=101 //первая страница issue проекта с id=101
/project?id=101&page=5 //пятая страница проекта с id =101

**Comment by grigoriy-romanenko** [comment]
готово
